config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'welcome/index'

  resources :help, only: [:index]
  resources :inputfiles, only: [:index, :new, :create, :destroy] do
    resources :orders, only: [:index]
  end

end

app/models/inputfile.rb
class Inputfile < ActiveRecord::Base
  mount_uploader :attachment, AttachmentUploader
  validates :name, presence: true, length: { maximum: 50 }
  validates :description, presence: true, length: { maximum: 255 }
  validate :all_validations

  def all_validations
    # Validations
    target_price_must_be_valid
    not_too_many_items
    validate_lines
  end

  def target_price_must_be_valid
    f = open_file
    line = f.readline
    if !valid_price?(line)
      errors.add(:line, "target price must be valid and less than 25,000")
    end
    f.close
  end

  def not_too_many_items
    f = open_file
    number_of_lines = f.read.count("\n")
    if number_of_lines > 1000
      errors.add(:number_of_items, "There are too many items in the file you are trying to input")
    end
    f.close
  end

  def validate_lines
    f = open_file
    line = f.readline
    # Read in remaining items
    f.each_line do |line|
      if !line.include?(",")
        errors.add(:file, "Does not include a comma delimited line")
        break
      end
      item_name = line.split(",")[0]
      item_price = line.split(",")[1].tr("$","").to_f
      item = Item.new(name: item_name, price: item_price)
      if !item.valid?
        errors.add(:item, "One of the uploaded items is not valid")
      end
    end
    f.close
  end

  private
  def valid_price?(string_value)
    string_value = string_value.tr("$","")
    if string_value.to_f != 0.0 || string_value == "0.0" && string_value.to_f < 25000
      return true
    else
      return false
    end
  end
  def open_file
    directory = "public"
    file_handle = File.open(File.join(directory, self.attachment_url), 'r')
    return file_handle
  end
end

app/controllers/inputfiles_controller.rb
class InputfilesController < ApplicationController
  def index
    @inputfiles = Inputfile.all
  end

  def new
    @inputfile = Inputfile.new
  end

  def create
    @inputfile = Inputfile.new(inputfile_params)
    puts inputfile_params
    if @inputfile.save
      redirect_to inputfiles_path, notice: "The input file #{@inputfile.name} has been uploaded"
    else
      render "new"
    end
  end

  def destroy
    @inputfile = Inputfile.find(params[:id])
    @inputfile.destroy
    redirect_to inputfiles_path,
    notice: "The input file #{@inputfile.name} has been deleted"
  end

  private
  def inputfile_params
    params.require(:inputfile).permit(:name, :attachment, :description)
  end
end

app/helpers/inputfiles_helper.rb
module InputfilesHelper
end

app/views/inputfiles/create.html.erb
<h1>Inputfiles#create</h1>
<p>Find me in app/views/inputfiles/create.html.erb</p>

app/views/inputfiles/destroy.html.erb
<h1>Inputfiles#destroy</h1>
<p>Find me in app/views/inputfiles/destroy.html.erb</p>

app/views/inputfiles/index.html.erb
<div class="container">
  <% if !flash[:notice].blank? %>
    <div class = "alert alert-info">
      <%= flash[:notice] %>
    </div>
  <% end %>

  <br />

  <%= link_to "New Input File", new_inputfile_path, class: "btn btn-primary" %>
  <br />
  <br />

  <table class = "table table-bordered table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Least items</th>
        <th>Most diverse</th>
        <th>Delete File</th>
      </tr>
    </thead>

    <tbody>
      <% @inputfiles.each do |inputfile| %>
        <% if inputfile.name != "Sample Menu 1" && inputfile.name != "Sample Menu 2" && inputfile.name != "Sample Menu 3" %>
          <tr>
            <td><%= inputfile.name %></td>
            <td><%= inputfile.description %></td>
            <td><%= button_to "Calculate", inputfile_orders_path(inputfile), method: :get, class: "btn btn-primary", params: {algorithm: 0} %></td>
            <td><%= button_to "Calculate", inputfile_orders_path(inputfile), method: :get, class: "btn btn-primary", params: {algorithm: 1} %></td>
            <td><%= button_to "Delete", inputfile, method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{inputfile.name}?" %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/inputfiles/new.html.erb
<div class="container">
  <% if !@inputfile.errors.empty? %>
    <div class = "alert alert-error">

      <ul>
        <% @inputfile.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>

    </div>
  <% end %>
  <div class = "well">
    <div class="container">
      <%= form_for @inputfile, html: { multipart: true } do |f| %>
        <p><%= f.label :name, "Menu Name"%></p>
        <p><%= f.text_field :name %></p>
        <p><%= f.label :description, "Menu Description" %></p>
        <p><%= f.text_area :description %></p>
        <p><%= f.label :attachment %><%= f.file_field :attachment %></p>
        <%= f.submit "Save", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>